# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: "kramdown"
repository: "ISSOtm/gb-asm-tutorial"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
include: ["_pages"]

collections:
  tutorial:
    output: true
    # The `lesson` layout relies on the permalink format
    permalink: /:path

# Front matter defaults
defaults:
  # Default locale for the site, which is in English
  - scope:
      path: ""
    values:
      locale: "en-US"
  # Specific configuration for the tutorial
  - scope:
      path: "_tutorial"
    values:
      layout: "lesson"
  # Locale for translations of the tutorial
  - scope:
      path: "_tutorial/en"
    values:
      locale: "en-US"
  ## ADD NEW TRANSLATIONS ABOVE THIS LINE


# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

baseurl: "/gb-asm-tutorial-v2" # the subpath of your site, e.g. /blog
url: "https://eldred.fr"
locale: "en-US"
#google_site_verification: "ljmYhpaVJNaCEk64aV0NyYzauKGSEUtOS2nsYEx7JD0"
title: "GB ASM Tutorial"
description: "A complete guide to programming Game Boy games in assembly."


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - LICENSE.md
  - README.md
